// Generated by gencpp from file Msgs/keyboardinput.msg
// DO NOT EDIT!


#ifndef MSGS_MESSAGE_KEYBOARDINPUT_H
#define MSGS_MESSAGE_KEYBOARDINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Msgs
{
template <class ContainerAllocator>
struct keyboardinput_
{
  typedef keyboardinput_<ContainerAllocator> Type;

  keyboardinput_()
    : command()  {
    }
  keyboardinput_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::Msgs::keyboardinput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Msgs::keyboardinput_<ContainerAllocator> const> ConstPtr;

}; // struct keyboardinput_

typedef ::Msgs::keyboardinput_<std::allocator<void> > keyboardinput;

typedef boost::shared_ptr< ::Msgs::keyboardinput > keyboardinputPtr;
typedef boost::shared_ptr< ::Msgs::keyboardinput const> keyboardinputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Msgs::keyboardinput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Msgs::keyboardinput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Msgs::keyboardinput_<ContainerAllocator1> & lhs, const ::Msgs::keyboardinput_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Msgs::keyboardinput_<ContainerAllocator1> & lhs, const ::Msgs::keyboardinput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Msgs::keyboardinput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Msgs::keyboardinput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Msgs::keyboardinput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Msgs::keyboardinput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Msgs::keyboardinput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Msgs::keyboardinput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Msgs::keyboardinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::Msgs::keyboardinput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::Msgs::keyboardinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Msgs/keyboardinput";
  }

  static const char* value(const ::Msgs::keyboardinput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Msgs::keyboardinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::Msgs::keyboardinput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Msgs::keyboardinput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct keyboardinput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Msgs::keyboardinput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Msgs::keyboardinput_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGS_MESSAGE_KEYBOARDINPUT_H
