// Generated by gencpp from file control/keyboardinput.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_KEYBOARDINPUT_H
#define CONTROL_MESSAGE_KEYBOARDINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control
{
template <class ContainerAllocator>
struct keyboardinput_
{
  typedef keyboardinput_<ContainerAllocator> Type;

  keyboardinput_()
    : command(0)  {
    }
  keyboardinput_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::control::keyboardinput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::keyboardinput_<ContainerAllocator> const> ConstPtr;

}; // struct keyboardinput_

typedef ::control::keyboardinput_<std::allocator<void> > keyboardinput;

typedef boost::shared_ptr< ::control::keyboardinput > keyboardinputPtr;
typedef boost::shared_ptr< ::control::keyboardinput const> keyboardinputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::keyboardinput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::keyboardinput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control::keyboardinput_<ContainerAllocator1> & lhs, const ::control::keyboardinput_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control::keyboardinput_<ContainerAllocator1> & lhs, const ::control::keyboardinput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control::keyboardinput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::keyboardinput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::keyboardinput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::keyboardinput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::keyboardinput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::keyboardinput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::keyboardinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf31d8a7def4ce3bca7e2b1b06a5b2a6";
  }

  static const char* value(const ::control::keyboardinput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf31d8a7def4ce3bULL;
  static const uint64_t static_value2 = 0xca7e2b1b06a5b2a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::control::keyboardinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/keyboardinput";
  }

  static const char* value(const ::control::keyboardinput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::keyboardinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char command\n"
;
  }

  static const char* value(const ::control::keyboardinput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::keyboardinput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct keyboardinput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::keyboardinput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::keyboardinput_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_KEYBOARDINPUT_H
